scrummer/scrum_reports/urls.py
from django.conf.urls import url
from scrum_reports.views import ReportView, HomeView, ReportDetailView, ScrumReportList


urlpatterns = [
    url(r'home/$', HomeView.as_view(), name='home'),
    url(r'reports/$', ReportView.as_view(), name='reports'),
    url(r'^report/(?P<pk>\d+)$', ReportDetailView.as_view(), name='report-detail'),
    url(r'list/$', ScrumReportList.as_view(), name='scrum-reports-list'),
]

scrummer/scrummer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

import debug_toolbar

urlpatterns = [
    url(r'^scrum-reports/', include('scrum_reports.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^$',
        RedirectView.as_view(url='/scrum-reports/home/', permanent=False)
    )
]

scrummer/scrum_reports/models.py
from django.contrib.auth.models import User
from django.db import models


class SignUp(models.Model):
    email = models.EmailField()
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.email


class ScrumReport(models.Model):
    person = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    report_since_last = models.TextField(blank=True)
    report_before_next = models.TextField(blank=True)
    report_issues = models.TextField(blank=True)

scrummer/scrum_reports/forms.py
from django import forms
from scrum_reports.models import SignUp, ScrumReport


class SignUpForm(forms.ModelForm):
    class Meta:
        model = SignUp
        fields = '__all__'


class ScrumReportForm(forms.ModelForm):
    class Meta:
        model = ScrumReport
        fields = '__all__'
        widgets = {
            '__all__': forms.Textarea(attrs={'rows': 2}),
        }

scrummer/scrum_reports/views.py
from django.views.generic import ListView, CreateView, DetailView
from scrum_reports.models import ScrumReport
from scrum_reports.forms import ScrumReportForm
from django.urls import reverse_lazy
from rest_framework import generics
from scrum_reports.serializers import ScrumReportSerializer


class ScrumReportList(generics.ListCreateAPIView):
    """
    API endpoint for listing and creating Book objects
    """
    queryset = ScrumReport.objects.all()
    serializer_class = ScrumReportSerializer


class HomeView(CreateView):
    template_name = 'scrum_reports/home.html'
    model = ScrumReport
    form_class = ScrumReportForm
    success_url = reverse_lazy('home')

    def scrumreports(self):
        return ScrumReport.objects.order_by('-created')[:3]


class ReportView(ListView):
    template_name = 'scrum_reports/reports.html'
    queryset = ScrumReport.objects.order_by('-created')
    paginate_by = 10


class ReportDetailView(DetailView):
    model = ScrumReport
    success_url = reverse_lazy('report-detail')

scrummer/scrum_reports/templates/scrum_reports/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

        <title>{% block head_title %}Infinite Scrummer{% endblock %}</title>
        
        {% include 'scrum_reports/head_css.html' %}

        <style>
         {% block style %}
         
         {% endblock %}
        </style>

    </head>

    <body>
        {% include 'scrum_reports/navbar.html' %}

        {% block main_bar %}
        
        {% endblock %}
        
        <div class="container">
            {% block content %}
            
            {% endblock %}

        </div>

        {% include 'scrum_reports/javascript.html' %}
    </body>
</html>

scrummer/scrum_reports/templates/scrum_reports/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        {% if title %}
        <h1 class="{% if title_align_center %}text-align-center{% endif %}">{{ title }}</h1>
        {% endif %}
        <form method="POST" action="">{%  csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-default" type="submit" value="Submit">
        </form>                 
    </div>

</div>

{% endblock %}
 

scrummer/scrum_reports/templates/scrum_reports/head_css.html
{% load static %}

<!-- Bootstrap core CSS -->
<link href="{% static 'scrum_reports/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{% static 'scrum_reports/css/navbar-static-top.css' %}" rel="stylesheet">
<link href="{% static 'scrum_reports/css/custom.css' %}" rel="stylesheet">
<link rel="stylesheet" src="https://npmcdn.com/react-bootstrap-table/dist/react-bootstrap-table-all.min.css"></link>    

scrummer/scrum_reports/templates/scrum_reports/home.html
{% extends "scrum_reports/base.html" %}
{% load crispy_forms_tags %}

{% load render_bundle from webpack_loader %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}

<style>
 {% block style %}
 .reportBtn {
     float: right;
 }
 label {
     padding-top: 15px;
     font-size: 20px;
 }
 textarea {
    height: 90px!important
 }
 .table {
     display:table;
     table-layout: fixed;
     word-wrap: break-word;
 }
 .table-row {
     display:table-row;
 }
 .table-cell {
     display:table-cell;
     word-wrap: break-word;
 }
 {% endblock %}
</style>

{% block main_bar %}


<div class="container">
    <div id="App"></div>
    <!-- <div class="row">
         <div class="col-lg-12 col-md-10 col-sm-8">
         {% if request.user.is_authenticated  %}
         <div class="table">
         <div class="table-row">
         <div class="table-cell col-lg-1"><h4>Person</h4></div>
         <div class="table-cell col-lg-3"><h4>Since Last</h4></div>
         <div class="table-cell col-lg-3"><h4>Before Next</h4></div>
         <div class="table-cell col-lg-3"><h4>Issues</h4></div>
         <div class="table-cell col-lg-2"><h4>Created</h4></div>
         </div>
         {% for row in view.scrumreports %}
         <a class="table-row" href="{% url 'report-detail' row.pk %}">
         <div class="table-cell col-lg-1">{{ row.person }}</div>
         <div class="table-cell col-lg-3">{{ row.report_since_last }}</div>
         <div class="table-cell col-lg-3">{{ row.report_before_next }}</div>
         <div class="table-cell col-lg-3">{{ row.report_issues }}</div>
         <div class="table-cell col-lg-2">{{ row.created|timesince }} ago</div>
         </a>
         {% endfor %}
         </div>
         <form  method="POST" action="">{%  csrf_token %}
         {{ form|crispy }}
         <button class="btn btn-default reportBtn" type="submit" >Report</button>
         </form>

         {% endif %}
         </div>
         </div>
       -->
         </div>

{% render_bundle 'App' %}

{% endblock %}

scrummer/scrum_reports/templates/scrum_reports/javascript.html
{% load static %} 


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="{% static 'scrum_reports/js/bootstrap.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'scrum_reports/js/ie10-viewport-bug-workaround.js' %}"></script>

scrummer/scrum_reports/templates/scrum_reports/navbar.html
{% load static %}

<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" id="logo" href="{% url 'home' %}"><img src="{% static 'scrum_reports/img/icon.png' %}"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li ><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'reports' %}">Reports</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                {% else %}  
                <li><a href="{% url 'registration_register' %}">Register</a></li>
                {% endif %}  
            </ul>
            {% if not request.user.is_authenticated and not '/accounts/login' in request.get_full_path %}
            <form class="navbar-form navbar-right" method="POST" action="{% url 'auth_login' %}">{% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" name="username" placeholder="Username">              
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="Password">              
                </div>
                <button type="submit" class="btn btn-default">Login</button>
            </form>
            {% endif %}  
        </div> <!--/.nav-collapse -->
    </div>
</nav>

scrummer/scrum_reports/templates/scrum_reports/reports.html
{% extends 'scrum_reports/base.html' %}
{% load crispy_forms_tags %}

<style>
{% block style %}
 /* table {
    table-layout: fixed;
    word-wrap: break-word;
    } */
.table {
    display:table;
    table-layout: fixed;
    word-wrap: break-word;
}
.table-row {
    display:table-row;
}
.table-cell {
    display:table-cell;
    word-wrap: break-word;
}
{% endblock  %}
</style>

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-10 col-sm-8">
            <h2>Full Reports</h2>

            {% if request.user.is_authenticated  %}
            <div class="table">
                <div class="table-row">
                    <div class="table-cell col-lg-1"><h4>Person</h4></div>
                    <div class="table-cell col-lg-3"><h4>Since Last</h4></div>
                    <div class="table-cell col-lg-3"><h4>Before Next</h4></div>
                    <div class="table-cell col-lg-3"><h4>Issues</h4></div>
                    <div class="table-cell col-lg-2"><h4>Created</h4></div>
                </div>
                {% for row in scrumreport_list %}
                <a class="table-row" href="{% url 'report-detail' row.pk %}">
                    <div class="table-cell col-lg-1">{{ row.person }}</div>
                    <div class="table-cell col-lg-3">{{ row.report_since_last }}</div>
                    <div class="table-cell col-lg-3">{{ row.report_before_next }}</div>
                    <div class="table-cell col-lg-3">{{ row.report_issues }}</div>
                    <div class="table-cell col-lg-2">{{ row.created|timesince }} ago</div>
                </a>
                {% endfor %}
            </div>

            {% endif %}

            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                            <span class="page-current">
                                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                            </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
            {% endblock %}

        </div>
    </div>

</div>

{% endblock %}

scrummer/scrum_reports/templates/scrum_reports/scrumreport_detail.html
{% extends 'scrum_reports/base.html' %}
{% load crispy_forms_tags %}

<style>
{% block style %}
 table {
     table-layout: fixed;
     word-wrap: break-word;
 }

{% endblock  %}
</style>

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-10 col-sm-8">
            {% if request.user.is_authenticated  %}

            <p><strong>Since Last: </strong>{{ object.report_since_last }}</p>
            <p><strong>Before Next: </strong>{{ object.report_before_next }}</p>
            <p><strong>Issues: </strong>{{ object.report_issues }}</p>
            <p><strong>Created: </strong>{{ object.created|timesince }} ago</p>

            {% endif %}
            <button class="btn btn-default">Update</button>
        </div>
    </div>
</div>

{% endblock %}